server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict

spring:
  jpa:
    show-sql: false

logging:
  level:
    io.epiphaneia: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.flywaydb: INFO
