spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epiphaneia_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

epiphaneia:
  encryption:
    key: ZGV2LWtleS1mb3ItZGV2ZWxvcG1lbnQtZW52aXJvbm1lbnQtb25seQ==

logging:
  level:
    io.epiphaneia: DEBUG
